### ISSUE TITLE
Can't install binding on just installed openhab

### ISSUE THREAD

**Issue by guyasyou** [Pshatsillo/openhab2MegadBinding#10]
Error in logs
```
2019-08-05 01:16:41.926 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.megad-2.5.0_1.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.megad [203]
  Unresolved requirement: Import-Package: org.apache.commons.codec.binary; version="[1.6.0,2.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [10:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [10:org.apache.felix.fileinstall:3.6.4]
```

openHAB 2.4.0

**Comment by guyasyou** [comment]
Solved!
Need to install HTTP binding
